/**
 * FILL THIS IN BEFORE RUNNING ANY SCRIPTS
 *
 * Find your tenant name by logging into office.com and looking at the URL.
 * If your SharePoint URL is https://ialta.sharepoint.com, your tenant is "ialta".
 */

module.exports = {
  // Your Microsoft 365 tenant name (the part before .sharepoint.com)
  tenant: 'ialta',

  // The name and URL slug for the course site
  // Site will be created at: https://[tenant].sharepoint.com/sites/[siteSlug]
  siteName: 'Citizen AI Developer Program',
  siteSlug: 'CitizenAI',

  // Description shown on the SharePoint site
  siteDescription: 'Internal training program for using Claude and AI tools effectively.',

  // Teams channel name for the course community
  teamsChannelName: 'Citizen AI Developer Program',

  // Path to the auth state file (generated by save-auth.js — do not edit)
  authStatePath: './auth/auth.json',

  // Path to course content directory
  contentDir: '../course-content',
};
